import { useDdxStore } from "@/stores/ddx-store"
import { useInsightsStore } from "@/stores/insights-store"
import { usePatientHandoutStore } from "@/stores/patient-handout-store"
import { useRecordStore } from "@/stores/record-store"
import { useResearchStore, type ResearchMessage } from "@/stores/research-store"
import { useNoteStore } from "@/stores/note-store"
import { useConsultationTabStore } from "@/stores/consultation-tab-store"
import { useDocumentWorkspaceStore } from "@/stores/document-workspace-store"
import { useSessionDocumentStore } from "@/stores/session-document-store"
import { useSessionStore } from "@/stores/session-store"
import {
  getTemplateIdFromTabId,
  isDocumentTabId,
} from "@/lib/documents/constants"
import {
  ddxToRichTextDocument,
  genericStructuredContentToRichTextDocument,
  insightsToRichTextDocument,
  isRichTextDocument,
  normalizeRichTextDocument,
  patientHandoutToRichTextDocument,
  recordToRichTextDocument,
  richTextDocumentToHtml,
  type RichTextDocument,
} from "@/lib/documents/rich-text"

const SYSTEM_TAB_LABELS = {
  insights: "Live Insights",
  ddx: "Differential Diagnosis",
  research: "Research",
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
}

function wrapInDocument(
  tabLabel: string,
  sessionTitle: string,
  patientName: string | null,
  bodyHtml: string
): string {
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  })
  const time = new Date().toLocaleTimeString("en-US", {
    hour: "2-digit",
    minute: "2-digit",
  })

  return `
<div style="max-width: 840px; margin: 0 auto; padding: 32px 24px 40px;">
  <div style="margin-bottom: 28px; padding-bottom: 18px; border-bottom: 1px solid #e5e7eb;">
    <div style="font-family: Geist, Inter, ui-sans-serif, sans-serif; font-size: 22px; font-weight: 700; color: #111827;">${escapeHtml(tabLabel)}</div>
    <p style="margin: 8px 0 0; font-family: Geist, Inter, ui-sans-serif, sans-serif; font-size: 12px; text-transform: uppercase; letter-spacing: 0.14em; color: #6b7280;">
      ${escapeHtml(sessionTitle)}${patientName ? ` · ${escapeHtml(patientName)}` : ""} · ${date}
    </p>
  </div>
  ${bodyHtml}
  <div style="margin-top: 36px; padding-top: 14px; border-top: 1px solid #e5e7eb; font-family: Geist, Inter, ui-sans-serif, sans-serif; font-size: 11px; color: #9ca3af;">
    Generated by Rxly on ${date} at ${time}
  </div>
</div>`
}

function formatResearchBody(messages: ResearchMessage[]): string {
  if (messages.length === 0) {
    return `<p style="font-family: Georgia, serif; font-size: 15px; color: #9ca3af; font-style: italic;">No research messages available.</p>`
  }

  return messages
    .map((msg) => {
      const isUser = msg.role === "user"
      const label = isUser ? "You" : "Rxly Research"
      const labelColor = isUser ? "#9a3412" : "#065f46"
      return `
<div style="margin-bottom: 12px; padding: 14px 16px; border: 1px solid #e5e7eb; border-radius: 16px; background: ${isUser ? "#fff7ed" : "#ffffff"};">
  <div style="margin-bottom: 6px; font-family: Geist, Inter, ui-sans-serif, sans-serif; font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.14em; color: ${labelColor};">${label}</div>
  <div style="font-family: Georgia, serif; font-size: 15px; line-height: 1.7; color: #374151; white-space: pre-wrap;">${escapeHtml(msg.content)}</div>
</div>`
    })
    .join("\n")
}

function resolveCustomDocument(
  sessionId: string,
  templateId: string
): RichTextDocument | null {
  const sessionDocumentStore = useSessionDocumentStore.getState()
  const workspaceStore = useDocumentWorkspaceStore.getState()
  const sessionDocument = sessionDocumentStore.getSessionDocument(sessionId, templateId)
  const installedDocument =
    workspaceStore.installedDocuments.find((document) => document.templateId === templateId) ??
    null

  if (!sessionDocument?.contentJson) return null

  if (isRichTextDocument(sessionDocument.contentJson)) {
    return normalizeRichTextDocument(sessionDocument.contentJson)
  }

  return genericStructuredContentToRichTextDocument({
    contentJson: sessionDocument.contentJson,
    schemaNodes:
      sessionDocument.templateSchemaNodes ??
      installedDocument?.installedVersionSchemaNodes,
  })
}

function resolveActiveDocumentHtml(): { bodyHtml: string; tabLabel: string } {
  const activeTab = useConsultationTabStore.getState().activeTab
  const session = useSessionStore.getState().activeSession
  const installedDocuments = useDocumentWorkspaceStore.getState().installedDocuments
  const templateId = isDocumentTabId(activeTab) ? getTemplateIdFromTabId(activeTab) : null
  const installedDocument = templateId
    ? installedDocuments.find((document) => document.templateId === templateId) ?? null
    : null
  const tabLabel =
    installedDocument?.title ||
    (activeTab in SYSTEM_TAB_LABELS
      ? SYSTEM_TAB_LABELS[activeTab as keyof typeof SYSTEM_TAB_LABELS]
      : "Document")

  if (activeTab === "research") {
    return {
      bodyHtml: formatResearchBody(useResearchStore.getState().messages),
      tabLabel,
    }
  }

  if (activeTab === "insights") {
    const insights = useInsightsStore.getState()
    const uploadedImages = useNoteStore.getState().notes.flatMap((note) =>
      (note.imageUrls || []).map((url) => ({
        url,
        alt: note.content || "Medical image",
      }))
    )
    const document = insightsToRichTextDocument({
      summary: insights.summary,
      keyFindings: insights.keyFindings,
      redFlags: insights.redFlags,
      checklistItems: insights.checklistItems,
      images: uploadedImages,
      labels: {
        summary: "Summary",
        keyFindings: "Key Findings",
        redFlags: "Red Flags",
        checklist: "Checklist",
        images: "Images",
      },
    })
    return {
      bodyHtml: richTextDocumentToHtml(document),
      tabLabel,
    }
  }

  if (activeTab === "ddx") {
    return {
      bodyHtml: richTextDocumentToHtml(
        ddxToRichTextDocument(useDdxStore.getState().diagnoses, {
          references: "References",
          evidence: "Evidence",
          confidence: "Confidence",
          icd: "ICD-11",
          referenceCount: "References",
        })
      ),
      tabLabel,
    }
  }

  if (installedDocument?.renderer === "BUILT_IN_RECORD") {
    const record = useRecordStore.getState().record
    const document = record
      ? normalizeRichTextDocument(
          record.documentJson,
          recordToRichTextDocument(record, {
            vitals: "Vitals",
            sections: {
              chiefComplaint: "Chief Complaint",
              hpiText: "History of Present Illness",
              medications: "Medications",
              rosText: "Review of Systems",
              pmh: "Past Medical History",
              socialHistory: "Social History",
              familyHistory: "Family History",
              physicalExam: "Physical Examination",
              labsStudies: "Labs and Studies",
              assessment: "Assessment",
              plan: "Plan",
            },
          })
        )
      : null
    return {
      bodyHtml: document
        ? richTextDocumentToHtml(document)
        : `<p style="font-family: Georgia, serif; font-size: 15px; color: #9ca3af; font-style: italic;">No consultation record available.</p>`,
      tabLabel,
    }
  }

  if (installedDocument?.renderer === "BUILT_IN_PATIENT_HANDOUT") {
    const patientHandout = usePatientHandoutStore.getState().document
    const document = patientHandout
      ? normalizeRichTextDocument(
          patientHandout.documentJson,
          patientHandoutToRichTextDocument(patientHandout, {
            sections: {
              conditionOverview: "Condition Overview",
              signsSymptoms: "Signs and Symptoms",
              causesRiskFactors: "Causes and Risk Factors",
              complications: "Complications",
              treatmentOptions: "Treatment Options",
              whenToSeekHelp: "When to Seek Help",
              additionalAdviceFollowUp: "Additional Advice and Follow-Up",
              disclaimer: "Disclaimer",
            },
          })
        )
      : null
    return {
      bodyHtml: document
        ? richTextDocumentToHtml(document)
        : `<p style="font-family: Georgia, serif; font-size: 15px; color: #9ca3af; font-style: italic;">No patient handout available.</p>`,
      tabLabel,
    }
  }

  if (session && templateId) {
    const document = resolveCustomDocument(session.id, templateId)
    return {
      bodyHtml: document
        ? richTextDocumentToHtml(document)
        : `<p style="font-family: Georgia, serif; font-size: 15px; color: #9ca3af; font-style: italic;">No document data available.</p>`,
      tabLabel,
    }
  }

  return {
    bodyHtml: `<p style="font-family: Georgia, serif; font-size: 15px; color: #9ca3af; font-style: italic;">No document data available.</p>`,
    tabLabel,
  }
}

export function getActiveTabExportHtml(): { html: string; tabLabel: string } {
  const session = useSessionStore.getState().activeSession
  const record = useRecordStore.getState().record
  const sessionTitle = session?.title || "Consultation"
  const patientName = record?.patientName || session?.patientName || null
  const { bodyHtml, tabLabel } = resolveActiveDocumentHtml()

  return {
    html: wrapInDocument(tabLabel, sessionTitle, patientName, bodyHtml),
    tabLabel,
  }
}

export async function generatePdf(): Promise<{ blob: Blob; filename: string }> {
  const { html, tabLabel } = getActiveTabExportHtml()
  const session = useSessionStore.getState().activeSession
  const sessionTitle = session?.title || "Consultation"
  const dateStr = new Date().toISOString().slice(0, 10)
  const filename = `${tabLabel.replace(/\s+/g, "-").toLowerCase()}-${sessionTitle.replace(/\s+/g, "-").toLowerCase()}-${dateStr}.pdf`

  interface Html2PdfWorker {
    from: (element: HTMLElement) => Html2PdfWorker
    set: (options: Record<string, unknown>) => Html2PdfWorker
    output: (type: "blob") => Promise<Blob>
  }

  type Html2PdfFactory = () => Html2PdfWorker

  const html2pdfModule = await import("html2pdf.js")
  const html2pdf = (
    "default" in html2pdfModule ? html2pdfModule.default : html2pdfModule
  ) as Html2PdfFactory

  const container = document.createElement("div")
  container.innerHTML = html
  container.style.position = "absolute"
  container.style.left = "-9999px"
  container.style.width = "840px"
  document.body.appendChild(container)

  const opt = {
    margin: [12, 0, 12, 0],
    filename,
    image: { type: "jpeg", quality: 0.98 },
    html2canvas: { scale: 2, useCORS: true, letterRendering: true },
    jsPDF: { unit: "mm", format: "a4", orientation: "portrait" },
    pagebreak: { mode: ["css", "legacy"] },
  }

  try {
    const blob = await html2pdf().from(container).set(opt).output("blob")
    return { blob, filename }
  } finally {
    document.body.removeChild(container)
  }
}
