import { useInsightsStore } from "@/stores/insights-store"
import { useDdxStore } from "@/stores/ddx-store"
import { useRecordStore } from "@/stores/record-store"
import { useResearchStore } from "@/stores/research-store"
import { usePatientHandoutStore } from "@/stores/patient-handout-store"
import { useSessionStore } from "@/stores/session-store"
import { useConsultationTabStore } from "@/stores/consultation-tab-store"
import type { ChecklistItem, DiagnosisItem } from "@/types/insights"
import type { ConsultationRecord } from "@/types/record"
import type { ResearchMessage } from "@/stores/research-store"
import {
  PATIENT_HANDOUT_SECTION_LABELS,
  type PatientHandoutDocument,
  type PatientHandoutSectionKey,
} from "@/types/patient-handout"

type Tab = "insights" | "ddx" | "record" | "research" | "patientHandout"

const TAB_LABELS: Record<Tab, string> = {
  insights: "Live Insights",
  ddx: "Differential Diagnosis",
  record: "Consultation Record",
  research: "Research",
  patientHandout: "Patient Handout",
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
}

// ── HTML formatters (used for email) ──

function wrapInDocument(
  tabLabel: string,
  sessionTitle: string,
  patientName: string | null,
  bodyHtml: string
): string {
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  })
  const time = new Date().toLocaleTimeString("en-US", {
    hour: "2-digit",
    minute: "2-digit",
  })

  return `
<div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 32px 24px; color: #1a1a1a; line-height: 1.6;">
  <div style="border-bottom: 2px solid #e5e7eb; padding-bottom: 16px; margin-bottom: 28px;">
    <div style="display: flex; align-items: center; gap: 8px; margin-bottom: 4px;">
      <span style="font-size: 20px; font-weight: 700; color: #111827;">Rxly</span>
      <span style="font-size: 14px; color: #9ca3af;">|</span>
      <span style="font-size: 16px; font-weight: 600; color: #374151;">${escapeHtml(tabLabel)}</span>
    </div>
    <p style="font-size: 13px; color: #6b7280; margin: 0;">
      ${escapeHtml(sessionTitle)}${patientName ? ` &middot; Patient: ${escapeHtml(patientName)}` : ""} &middot; ${date}
    </p>
  </div>
  ${bodyHtml}
  <div style="border-top: 1px solid #e5e7eb; padding-top: 12px; margin-top: 36px;">
    <p style="font-size: 11px; color: #9ca3af; margin: 0;">
      Generated by Rxly on ${date} at ${time}
    </p>
  </div>
</div>`
}

function sectionTitle(title: string): string {
  return `<h2 style="font-size: 15px; font-weight: 600; color: #111827; margin: 24px 0 8px 0; padding-bottom: 4px; border-bottom: 1px solid #f3f4f6;">${escapeHtml(title)}</h2>`
}

function formatInsightsBody(
  summary: string,
  keyFindings: string[],
  redFlags: string[],
  checklistItems: ChecklistItem[]
): string {
  const parts: string[] = []

  if (summary) {
    parts.push(sectionTitle("Summary"))
    parts.push(
      `<p style="font-size: 14px; color: #374151; margin: 0;">${escapeHtml(summary)}</p>`
    )
  }

  if (keyFindings.length > 0) {
    parts.push(sectionTitle("Key Findings"))
    parts.push('<ul style="margin: 0; padding-left: 20px;">')
    keyFindings.forEach((f) => {
      parts.push(
        `<li style="font-size: 14px; color: #374151; margin-bottom: 4px;">${escapeHtml(f)}</li>`
      )
    })
    parts.push("</ul>")
  }

  if (redFlags.length > 0) {
    parts.push(sectionTitle("Red Flags"))
    parts.push('<ul style="margin: 0; padding-left: 20px;">')
    redFlags.forEach((f) => {
      parts.push(
        `<li style="font-size: 14px; color: #dc2626; margin-bottom: 4px;">&#9888; ${escapeHtml(f)}</li>`
      )
    })
    parts.push("</ul>")
  }

  if (checklistItems.length > 0) {
    parts.push(sectionTitle("Checklist"))
    checklistItems.forEach((item) => {
      const icon = item.isChecked ? "&#9745;" : "&#9744;"
      const style = item.isChecked
        ? "color: #6b7280; text-decoration: line-through;"
        : "color: #374151;"
      parts.push(
        `<div style="font-size: 14px; ${style} margin-bottom: 4px;">${icon} ${escapeHtml(item.label)}</div>`
      )
      if (item.doctorNote) {
        parts.push(
          `<div style="font-size: 12px; color: #6b7280; margin-left: 24px; margin-bottom: 6px; font-style: italic;">Note: ${escapeHtml(item.doctorNote)}</div>`
        )
      }
    })
  }

  if (parts.length === 0) {
    parts.push(
      `<p style="font-size: 14px; color: #9ca3af; font-style: italic;">No insights data available.</p>`
    )
  }

  return parts.join("\n")
}

function formatDdxBody(diagnoses: DiagnosisItem[]): string {
  if (diagnoses.length === 0) {
    return `<p style="font-size: 14px; color: #9ca3af; font-style: italic;">No differential diagnoses available.</p>`
  }

  const confidenceColors: Record<string, string> = {
    high: "#16a34a",
    moderate: "#d97706",
    low: "#dc2626",
  }

  const parts: string[] = []

  diagnoses.forEach((dx, i) => {
    const color = confidenceColors[dx.confidence] || "#6b7280"
    parts.push(`
<div style="border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; margin-bottom: 12px;">
  <div style="display: flex; align-items: center; gap: 8px; margin-bottom: 8px;">
    <span style="font-size: 14px; font-weight: 600; color: #111827;">${i + 1}. ${escapeHtml(dx.diseaseName)}</span>
    <span style="font-size: 11px; padding: 2px 8px; border-radius: 9999px; background: ${color}18; color: ${color}; font-weight: 500;">${dx.confidence}</span>
  </div>
  <div style="font-size: 12px; color: #6b7280; margin-bottom: 6px;">ICD: ${escapeHtml(dx.icdCode)}</div>
  <div style="font-size: 13px; color: #374151;">${escapeHtml(dx.evidence)}</div>
  ${
    dx.citations.length > 0
      ? `<div style="margin-top: 8px; padding-top: 8px; border-top: 1px solid #f3f4f6;">
          <div style="font-size: 11px; font-weight: 600; color: #6b7280; margin-bottom: 4px;">References</div>
          ${dx.citations
            .map(
              (c) =>
                `<div style="font-size: 11px; color: #6b7280; margin-bottom: 2px;">&bull; [${escapeHtml(c.source.toUpperCase())}] <a href="${escapeHtml(c.url)}" style="color: #2563eb;">${escapeHtml(c.title)}</a></div>`
            )
            .join("\n")}
        </div>`
      : ""
  }
</div>`)
  })

  return parts.join("\n")
}

function formatRecordBody(record: ConsultationRecord | null): string {
  if (!record) {
    return `<p style="font-size: 14px; color: #9ca3af; font-style: italic;">No consultation record available.</p>`
  }

  const parts: string[] = []

  if (record.vitals) {
    const v = record.vitals
    const vitals = [
      { label: "BP", value: v.bp },
      { label: "HR", value: v.hr },
      { label: "Temp", value: v.temp },
      { label: "RR", value: v.rr },
      { label: "SpO2", value: v.spo2 },
    ].filter((x) => x.value)

    if (vitals.length > 0) {
      parts.push(sectionTitle("Vitals"))
      parts.push(
        `<table style="border-collapse: collapse; width: 100%; margin-bottom: 8px;">`
      )
      parts.push(
        `<tr>${vitals.map((x) => `<td style="padding: 6px 12px; border: 1px solid #e5e7eb; font-size: 12px; font-weight: 600; color: #6b7280; background: #f9fafb;">${x.label}</td>`).join("")}</tr>`
      )
      parts.push(
        `<tr>${vitals.map((x) => `<td style="padding: 6px 12px; border: 1px solid #e5e7eb; font-size: 13px; color: #374151;">${escapeHtml(x.value)}</td>`).join("")}</tr>`
      )
      parts.push(`</table>`)
    }
  }

  const sections: { label: string; value: string | null }[] = [
    { label: "Chief Complaint", value: record.chiefComplaint },
    { label: "History of Present Illness", value: record.hpiText },
    { label: "Current Medications", value: record.medications },
    { label: "Review of Systems", value: record.rosText },
    { label: "Past Medical History", value: record.pmh },
    { label: "Social History", value: record.socialHistory },
    { label: "Family History", value: record.familyHistory },
    { label: "Physical Exam", value: record.physicalExam },
    { label: "Labs / Studies", value: record.labsStudies },
    { label: "Assessment", value: record.assessment },
    { label: "Plan", value: record.plan },
  ]

  sections.forEach(({ label, value }) => {
    if (value) {
      parts.push(sectionTitle(label))
      const formatted = escapeHtml(value).replace(/\n/g, "<br/>")
      parts.push(
        `<p style="font-size: 14px; color: #374151; margin: 0; white-space: pre-wrap;">${formatted}</p>`
      )
    }
  })

  if (parts.length === 0) {
    parts.push(
      `<p style="font-size: 14px; color: #9ca3af; font-style: italic;">Record is empty.</p>`
    )
  }

  return parts.join("\n")
}

function formatResearchBody(messages: ResearchMessage[]): string {
  if (messages.length === 0) {
    return `<p style="font-size: 14px; color: #9ca3af; font-style: italic;">No research messages available.</p>`
  }

  const parts: string[] = []

  messages.forEach((msg) => {
    const isUser = msg.role === "user"
    const bgColor = isUser ? "#eff6ff" : "#ffffff"
    const borderColor = isUser ? "#bfdbfe" : "#e5e7eb"
    const label = isUser ? "You" : "Rxly Research"
    const labelColor = isUser ? "#2563eb" : "#059669"

    parts.push(`
<div style="border: 1px solid ${borderColor}; border-radius: 8px; padding: 12px 16px; margin-bottom: 8px; background: ${bgColor};">
  <div style="font-size: 11px; font-weight: 600; color: ${labelColor}; margin-bottom: 4px;">${label}</div>
  <div style="font-size: 13px; color: #374151; white-space: pre-wrap;">${escapeHtml(msg.content)}</div>
  ${
    msg.citations.length > 0
      ? `<div style="margin-top: 8px; padding-top: 6px; border-top: 1px solid ${borderColor};">
          ${msg.citations
            .map(
              (c) =>
                `<div style="font-size: 11px; color: #6b7280; margin-bottom: 2px;">&bull; [${escapeHtml(c.source.toUpperCase())}] <a href="${escapeHtml(c.url)}" style="color: #2563eb;">${escapeHtml(c.title)}</a></div>`
            )
            .join("\n")}
        </div>`
      : ""
  }
</div>`)
  })

  return parts.join("\n")
}

function formatPatientHandoutBody(document: PatientHandoutDocument | null): string {
  if (!document || document.conditions.length === 0) {
    return `<p style="font-size: 14px; color: #9ca3af; font-style: italic;">No patient handout available.</p>`
  }

  const sectionOrder: PatientHandoutSectionKey[] = [
    "conditionOverview",
    "signsSymptoms",
    "causesRiskFactors",
    "complications",
    "treatmentOptions",
    "whenToSeekHelp",
    "additionalAdviceFollowUp",
    "disclaimer",
  ]

  const entryMap = new Map(
    document.entries.map((entry) => [entry.conditionId, entry])
  )

  const parts: string[] = []

  document.conditions.forEach((condition) => {
    const entry = entryMap.get(condition.id)
    parts.push(
      `<div style="border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; margin-bottom: 16px;">`
    )
    parts.push(
      `<h2 style="font-size: 16px; margin: 0 0 2px 0; color: #111827;">${escapeHtml(condition.diseaseName)}</h2>`
    )
    parts.push(
      `<p style="font-size: 12px; margin: 0 0 12px 0; color: #6b7280;">ICD-11: ${escapeHtml(condition.icdCode)}</p>`
    )

    sectionOrder.forEach((sectionKey) => {
      const titleText = PATIENT_HANDOUT_SECTION_LABELS[sectionKey]
      const value = entry?.sections[sectionKey] || ""
      parts.push(sectionTitle(titleText))
      parts.push(
        `<p style="font-size: 14px; color: #374151; margin: 0; white-space: pre-wrap;">${escapeHtml(value || "[Not provided]")}</p>`
      )
    })

    parts.push(`</div>`)
  })

  return parts.join("\n")
}

// ── HTML export (used for email) ──

export function getActiveTabExportHtml(): { html: string; tabLabel: string } {
  const activeTab = useConsultationTabStore.getState().activeTab
  const session = useSessionStore.getState().activeSession
  const sessionTitle = session?.title || "Consultation"
  const tabLabel = TAB_LABELS[activeTab]

  const record = useRecordStore.getState().record
  const patientName = record?.patientName || null

  let bodyHtml = ""

  switch (activeTab) {
    case "insights": {
      const { summary, keyFindings, redFlags, checklistItems } =
        useInsightsStore.getState()
      bodyHtml = formatInsightsBody(
        summary,
        keyFindings,
        redFlags,
        checklistItems
      )
      break
    }
    case "ddx": {
      const { diagnoses } = useDdxStore.getState()
      bodyHtml = formatDdxBody(diagnoses)
      break
    }
    case "record": {
      bodyHtml = formatRecordBody(record)
      break
    }
    case "research": {
      const { messages } = useResearchStore.getState()
      bodyHtml = formatResearchBody(messages)
      break
    }
    case "patientHandout": {
      const { document } = usePatientHandoutStore.getState()
      bodyHtml = formatPatientHandoutBody(document)
      break
    }
  }

  return {
    html: wrapInDocument(tabLabel, sessionTitle, patientName, bodyHtml),
    tabLabel,
  }
}

// ── jsPDF-based PDF generation (no html2canvas) ──

type RGB = [number, number, number]

const COLORS = {
  black: [17, 24, 39] as RGB,
  gray: [107, 114, 128] as RGB,
  lightGray: [156, 163, 175] as RGB,
  red: [220, 38, 38] as RGB,
  green: [22, 163, 74] as RGB,
  amber: [217, 119, 6] as RGB,
  blue: [37, 99, 235] as RGB,
  teal: [5, 150, 105] as RGB,
  lineColor: [229, 231, 235] as RGB,
}

interface PdfWriter {
  y: number
  doc: import("jspdf").jsPDF
  pageWidth: number
  pageHeight: number
  margin: number
  contentWidth: number
}

function checkPageBreak(w: PdfWriter, neededHeight: number) {
  if (w.y + neededHeight > w.pageHeight - w.margin) {
    w.doc.addPage()
    w.y = w.margin
  }
}

function drawLine(w: PdfWriter) {
  w.doc.setDrawColor(...COLORS.lineColor)
  w.doc.setLineWidth(0.3)
  w.doc.line(w.margin, w.y, w.margin + w.contentWidth, w.y)
  w.y += 4
}

function writeText(
  w: PdfWriter,
  text: string,
  opts: {
    fontSize?: number
    color?: RGB
    bold?: boolean
    indent?: number
    lineHeight?: number
    prefix?: string
  } = {}
) {
  const {
    fontSize = 10,
    color = COLORS.black,
    bold = false,
    indent = 0,
    lineHeight = 1.4,
    prefix,
  } = opts

  w.doc.setFontSize(fontSize)
  w.doc.setTextColor(...color)
  w.doc.setFont("helvetica", bold ? "bold" : "normal")

  const x = w.margin + indent
  const maxWidth = w.contentWidth - indent

  // Split text into lines that fit
  const lines = w.doc.splitTextToSize(text, maxWidth)

  for (let i = 0; i < lines.length; i++) {
    const lineText = i === 0 && prefix ? `${prefix}${lines[i]}` : lines[i]
    const h = fontSize * 0.353 * lineHeight // pt to mm, with line height
    checkPageBreak(w, h)
    w.doc.text(lineText, x, w.y)
    w.y += h
  }
}

function writeSectionTitle(w: PdfWriter, title: string) {
  w.y += 4
  checkPageBreak(w, 12)
  writeText(w, title, { fontSize: 12, bold: true, color: COLORS.black })
  w.y += 1
  drawLine(w)
}

function writeInsightsPdf(w: PdfWriter) {
  const { summary, keyFindings, redFlags, checklistItems } =
    useInsightsStore.getState()

  if (summary) {
    writeSectionTitle(w, "Summary")
    writeText(w, summary, { color: COLORS.black })
  }

  if (keyFindings.length > 0) {
    writeSectionTitle(w, "Key Findings")
    keyFindings.forEach((f) => {
      writeText(w, f, { indent: 4, prefix: "\u2022 " })
      w.y += 1
    })
  }

  if (redFlags.length > 0) {
    writeSectionTitle(w, "Red Flags")
    redFlags.forEach((f) => {
      writeText(w, f, { indent: 4, color: COLORS.red, prefix: "\u26A0 " })
      w.y += 1
    })
  }

  if (checklistItems.length > 0) {
    writeSectionTitle(w, "Checklist")
    checklistItems.forEach((item) => {
      const icon = item.isChecked ? "\u2611" : "\u2610"
      const color = item.isChecked ? COLORS.gray : COLORS.black
      writeText(w, `${icon} ${item.label}`, { indent: 4, color })
      if (item.doctorNote) {
        writeText(w, `Note: ${item.doctorNote}`, {
          indent: 12,
          fontSize: 9,
          color: COLORS.gray,
        })
      }
      w.y += 1
    })
  }

  if (!summary && keyFindings.length === 0 && redFlags.length === 0 && checklistItems.length === 0) {
    writeText(w, "No insights data available.", { color: COLORS.lightGray })
  }
}

function writeDdxPdf(w: PdfWriter) {
  const { diagnoses } = useDdxStore.getState()

  if (diagnoses.length === 0) {
    writeText(w, "No differential diagnoses available.", {
      color: COLORS.lightGray,
    })
    return
  }

  const confidenceColor: Record<string, RGB> = {
    high: COLORS.green,
    moderate: COLORS.amber,
    low: COLORS.red,
  }

  diagnoses.forEach((dx, i) => {
    checkPageBreak(w, 20)
    w.y += 3

    // Disease name + confidence
    const confColor = confidenceColor[dx.confidence] || COLORS.gray
    writeText(w, `${i + 1}. ${dx.diseaseName}`, {
      fontSize: 11,
      bold: true,
    })
    // Confidence on same conceptual block
    writeText(w, `Confidence: ${dx.confidence}`, {
      fontSize: 9,
      color: confColor,
      indent: 4,
    })

    // ICD code
    writeText(w, `ICD: ${dx.icdCode}`, {
      fontSize: 9,
      color: COLORS.gray,
      indent: 4,
    })
    w.y += 1

    // Evidence
    writeText(w, dx.evidence, { indent: 4, fontSize: 9.5 })

    // Citations
    if (dx.citations.length > 0) {
      w.y += 2
      writeText(w, "References:", {
        fontSize: 8,
        bold: true,
        color: COLORS.gray,
        indent: 4,
      })
      dx.citations.forEach((c) => {
        writeText(
          w,
          `[${c.source.toUpperCase()}] ${c.title}`,
          { fontSize: 8, color: COLORS.gray, indent: 8 }
        )
      })
    }

    w.y += 2
    drawLine(w)
  })
}

function writeRecordPdf(w: PdfWriter) {
  const { record } = useRecordStore.getState()

  if (!record) {
    writeText(w, "No consultation record available.", {
      color: COLORS.lightGray,
    })
    return
  }

  // Vitals
  if (record.vitals) {
    const v = record.vitals
    const vitals = [
      { label: "BP", value: v.bp },
      { label: "HR", value: v.hr },
      { label: "Temp", value: v.temp },
      { label: "RR", value: v.rr },
      { label: "SpO2", value: v.spo2 },
    ].filter((x) => x.value)

    if (vitals.length > 0) {
      writeSectionTitle(w, "Vitals")
      const row = vitals.map((x) => `${x.label}: ${x.value}`).join("   |   ")
      writeText(w, row, { fontSize: 10 })
    }
  }

  const sections: { label: string; value: string | null }[] = [
    { label: "Chief Complaint", value: record.chiefComplaint },
    { label: "History of Present Illness", value: record.hpiText },
    { label: "Current Medications", value: record.medications },
    { label: "Review of Systems", value: record.rosText },
    { label: "Past Medical History", value: record.pmh },
    { label: "Social History", value: record.socialHistory },
    { label: "Family History", value: record.familyHistory },
    { label: "Physical Exam", value: record.physicalExam },
    { label: "Labs / Studies", value: record.labsStudies },
    { label: "Assessment", value: record.assessment },
    { label: "Plan", value: record.plan },
  ]

  sections.forEach(({ label, value }) => {
    if (value) {
      writeSectionTitle(w, label)
      writeText(w, value, { fontSize: 10 })
    }
  })
}

function writeResearchPdf(w: PdfWriter) {
  const { messages } = useResearchStore.getState()

  if (messages.length === 0) {
    writeText(w, "No research messages available.", {
      color: COLORS.lightGray,
    })
    return
  }

  messages.forEach((msg) => {
    const isUser = msg.role === "user"
    const label = isUser ? "You" : "Rxly Research"
    const labelColor = isUser ? COLORS.blue : COLORS.teal

    checkPageBreak(w, 12)
    w.y += 3
    writeText(w, label, { fontSize: 9, bold: true, color: labelColor })
    writeText(w, msg.content, { fontSize: 10 })

    if (msg.citations.length > 0) {
      w.y += 1
      msg.citations.forEach((c) => {
        writeText(
          w,
          `[${c.source.toUpperCase()}] ${c.title}`,
          { fontSize: 8, color: COLORS.gray, indent: 4 }
        )
      })
    }

    w.y += 2
    drawLine(w)
  })
}

function writePatientHandoutPdf(w: PdfWriter) {
  const { document } = usePatientHandoutStore.getState()

  if (!document || document.conditions.length === 0) {
    writeText(w, "No patient handout available.", {
      color: COLORS.lightGray,
    })
    return
  }

  const sectionOrder: PatientHandoutSectionKey[] = [
    "conditionOverview",
    "signsSymptoms",
    "causesRiskFactors",
    "complications",
    "treatmentOptions",
    "whenToSeekHelp",
    "additionalAdviceFollowUp",
    "disclaimer",
  ]

  const entryMap = new Map(
    document.entries.map((entry) => [entry.conditionId, entry])
  )

  document.conditions.forEach((condition, index) => {
    if (index > 0) {
      w.y += 3
      drawLine(w)
      w.y += 3
    }

    writeText(w, `${condition.diseaseName} (${condition.icdCode})`, {
      fontSize: 12,
      bold: true,
    })

    const entry = entryMap.get(condition.id)
    sectionOrder.forEach((sectionKey) => {
      const label = PATIENT_HANDOUT_SECTION_LABELS[sectionKey]
      writeSectionTitle(w, label)
      writeText(w, entry?.sections[sectionKey] || "[Not provided]", {
        fontSize: 10,
      })
    })
  })
}

export async function generatePdf(): Promise<{ blob: Blob; filename: string }> {
  const { jsPDF } = await import("jspdf")

  const activeTab = useConsultationTabStore.getState().activeTab
  const session = useSessionStore.getState().activeSession
  const sessionTitle = session?.title || "Consultation"
  const tabLabel = TAB_LABELS[activeTab]
  const record = useRecordStore.getState().record
  const patientName = record?.patientName || null

  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  })
  const time = new Date().toLocaleTimeString("en-US", {
    hour: "2-digit",
    minute: "2-digit",
  })

  const doc = new jsPDF({ unit: "mm", format: "a4", orientation: "portrait" })
  const margin = 15
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const contentWidth = pageWidth - margin * 2

  const w: PdfWriter = { y: margin, doc, pageWidth, pageHeight, margin, contentWidth }

  // Header
  writeText(w, "Rxly", { fontSize: 18, bold: true })
  writeText(w, tabLabel, { fontSize: 13, bold: true, color: COLORS.gray })
  w.y += 2
  const subtitle = `${sessionTitle}${patientName ? ` | Patient: ${patientName}` : ""} | ${date}`
  writeText(w, subtitle, { fontSize: 9, color: COLORS.gray })
  w.y += 2
  drawLine(w)
  w.y += 2

  // Body
  switch (activeTab) {
    case "insights":
      writeInsightsPdf(w)
      break
    case "ddx":
      writeDdxPdf(w)
      break
    case "record":
      writeRecordPdf(w)
      break
    case "research":
      writeResearchPdf(w)
      break
    case "patientHandout":
      writePatientHandoutPdf(w)
      break
  }

  // Footer
  w.y += 6
  drawLine(w)
  writeText(w, `Generated by Rxly on ${date} at ${time}`, {
    fontSize: 8,
    color: COLORS.lightGray,
  })

  const dateStr = new Date().toISOString().slice(0, 10)
  const filename = `${tabLabel.replace(/\s+/g, "-").toLowerCase()}-${sessionTitle.replace(/\s+/g, "-").toLowerCase()}-${dateStr}.pdf`

  return { blob: doc.output("blob"), filename }
}
