import { useInsightsStore } from "@/stores/insights-store"
import { useDdxStore } from "@/stores/ddx-store"
import { useRecordStore } from "@/stores/record-store"
import { useResearchStore } from "@/stores/research-store"
import { usePatientHandoutStore } from "@/stores/patient-handout-store"
import { useSessionStore } from "@/stores/session-store"
import { useConsultationTabStore } from "@/stores/consultation-tab-store"
import type { ChecklistItem, DiagnosisItem } from "@/types/insights"
import type { ConsultationRecord } from "@/types/record"
import type { ResearchMessage } from "@/stores/research-store"
import {
  PATIENT_HANDOUT_SECTION_LABELS,
  type PatientHandoutDocument,
  type PatientHandoutSectionKey,
} from "@/types/patient-handout"

type Tab = "insights" | "ddx" | "record" | "research" | "patientHandout"

const TAB_LABELS: Record<Tab, string> = {
  insights: "Live Insights",
  ddx: "Differential Diagnosis",
  record: "Consultation Record",
  research: "Research",
  patientHandout: "Patient Handout",
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
}

// ── HTML formatters (used for email) ──

function wrapInDocument(
  tabLabel: string,
  sessionTitle: string,
  patientName: string | null,
  bodyHtml: string
): string {
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  })
  const time = new Date().toLocaleTimeString("en-US", {
    hour: "2-digit",
    minute: "2-digit",
  })

  return `
<div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 32px 24px; color: #1a1a1a; line-height: 1.6;">
  <div style="border-bottom: 2px solid #e5e7eb; padding-bottom: 16px; margin-bottom: 28px;">
    <div style="display: flex; align-items: center; gap: 8px; margin-bottom: 4px;">
      <span style="font-size: 20px; font-weight: 700; color: #111827;">Rxly</span>
      <span style="font-size: 14px; color: #9ca3af;">|</span>
      <span style="font-size: 16px; font-weight: 600; color: #374151;">${escapeHtml(tabLabel)}</span>
    </div>
    <p style="font-size: 13px; color: #6b7280; margin: 0;">
      ${escapeHtml(sessionTitle)}${patientName ? ` &middot; Patient: ${escapeHtml(patientName)}` : ""} &middot; ${date}
    </p>
  </div>
  ${bodyHtml}
  <div style="border-top: 1px solid #e5e7eb; padding-top: 12px; margin-top: 36px;">
    <p style="font-size: 11px; color: #9ca3af; margin: 0;">
      Generated by Rxly on ${date} at ${time}
    </p>
  </div>
</div>`
}

function sectionTitle(title: string): string {
  return `<h2 style="font-size: 15px; font-weight: 600; color: #111827; margin: 24px 0 8px 0; padding-bottom: 4px; border-bottom: 1px solid #f3f4f6;">${escapeHtml(title)}</h2>`
}

function formatInsightsBody(
  summary: string,
  keyFindings: string[],
  redFlags: string[],
  checklistItems: ChecklistItem[]
): string {
  const parts: string[] = []

  if (summary) {
    parts.push(sectionTitle("Summary"))
    parts.push(
      `<p style="font-size: 14px; color: #374151; margin: 0;">${escapeHtml(summary)}</p>`
    )
  }

  if (keyFindings.length > 0) {
    parts.push(sectionTitle("Key Findings"))
    parts.push('<ul style="margin: 0; padding-left: 20px;">')
    keyFindings.forEach((f) => {
      parts.push(
        `<li style="font-size: 14px; color: #374151; margin-bottom: 4px;">${escapeHtml(f)}</li>`
      )
    })
    parts.push("</ul>")
  }

  if (redFlags.length > 0) {
    parts.push(sectionTitle("Red Flags"))
    parts.push('<ul style="margin: 0; padding-left: 20px;">')
    redFlags.forEach((f) => {
      parts.push(
        `<li style="font-size: 14px; color: #dc2626; margin-bottom: 4px;">&#9888; ${escapeHtml(f)}</li>`
      )
    })
    parts.push("</ul>")
  }

  if (checklistItems.length > 0) {
    parts.push(sectionTitle("Checklist"))
    checklistItems.forEach((item) => {
      const icon = item.isChecked ? "&#9745;" : "&#9744;"
      const style = item.isChecked
        ? "color: #6b7280; text-decoration: line-through;"
        : "color: #374151;"
      parts.push(
        `<div style="font-size: 14px; ${style} margin-bottom: 4px;">${icon} ${escapeHtml(item.label)}</div>`
      )
      if (item.doctorNote) {
        parts.push(
          `<div style="font-size: 12px; color: #6b7280; margin-left: 24px; margin-bottom: 6px; font-style: italic;">Note: ${escapeHtml(item.doctorNote)}</div>`
        )
      }
    })
  }

  if (parts.length === 0) {
    parts.push(
      `<p style="font-size: 14px; color: #9ca3af; font-style: italic;">No insights data available.</p>`
    )
  }

  return parts.join("\n")
}

function formatDdxBody(diagnoses: DiagnosisItem[]): string {
  if (diagnoses.length === 0) {
    return `<p style="font-size: 14px; color: #9ca3af; font-style: italic;">No differential diagnoses available.</p>`
  }

  const confidenceColors: Record<string, string> = {
    high: "#16a34a",
    moderate: "#d97706",
    low: "#dc2626",
  }

  const parts: string[] = []

  diagnoses.forEach((dx, i) => {
    const color = confidenceColors[dx.confidence] || "#6b7280"
    parts.push(`
<div style="border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; margin-bottom: 12px;">
  <div style="display: flex; align-items: center; gap: 8px; margin-bottom: 8px;">
    <span style="font-size: 14px; font-weight: 600; color: #111827;">${i + 1}. ${escapeHtml(dx.diseaseName)}</span>
    <span style="font-size: 11px; padding: 2px 8px; border-radius: 9999px; background: ${color}18; color: ${color}; font-weight: 500;">${dx.confidence}</span>
  </div>
  <div style="font-size: 12px; color: #6b7280; margin-bottom: 6px;">ICD: ${escapeHtml(dx.icdCode)}</div>
  <div style="font-size: 13px; color: #374151;">${escapeHtml(dx.evidence)}</div>
  ${dx.citations.length > 0
        ? `<div style="margin-top: 8px; padding-top: 8px; border-top: 1px solid #f3f4f6;">
          <div style="font-size: 11px; font-weight: 600; color: #6b7280; margin-bottom: 4px;">References</div>
          ${dx.citations
          .map(
            (c) =>
              `<div style="font-size: 11px; color: #6b7280; margin-bottom: 2px;">&bull; [${escapeHtml(c.source.toUpperCase())}] <a href="${escapeHtml(c.url)}" style="color: #2563eb;">${escapeHtml(c.title)}</a></div>`
          )
          .join("\n")}
        </div>`
        : ""
      }
</div>`)
  })

  return parts.join("\n")
}

function formatRecordBody(record: ConsultationRecord | null): string {
  if (!record) {
    return `<p style="font-size: 14px; color: #9ca3af; font-style: italic;">No consultation record available.</p>`
  }

  const parts: string[] = []

  if (record.vitals) {
    const v = record.vitals
    const vitals = [
      { label: "BP", value: v.bp },
      { label: "HR", value: v.hr },
      { label: "Temp", value: v.temp },
      { label: "RR", value: v.rr },
      { label: "SpO2", value: v.spo2 },
    ].filter((x) => x.value)

    if (vitals.length > 0) {
      parts.push(sectionTitle("Vitals"))
      parts.push(
        `<table style="border-collapse: collapse; width: 100%; margin-bottom: 8px;">`
      )
      parts.push(
        `<tr>${vitals.map((x) => `<td style="padding: 6px 12px; border: 1px solid #e5e7eb; font-size: 12px; font-weight: 600; color: #6b7280; background: #f9fafb;">${x.label}</td>`).join("")}</tr>`
      )
      parts.push(
        `<tr>${vitals.map((x) => `<td style="padding: 6px 12px; border: 1px solid #e5e7eb; font-size: 13px; color: #374151;">${escapeHtml(x.value)}</td>`).join("")}</tr>`
      )
      parts.push(`</table>`)
    }
  }

  const sections: { label: string; value: string | null }[] = [
    { label: "Chief Complaint", value: record.chiefComplaint },
    { label: "History of Present Illness", value: record.hpiText },
    { label: "Current Medications", value: record.medications },
    { label: "Review of Systems", value: record.rosText },
    { label: "Past Medical History", value: record.pmh },
    { label: "Social History", value: record.socialHistory },
    { label: "Family History", value: record.familyHistory },
    { label: "Physical Exam", value: record.physicalExam },
    { label: "Labs / Studies", value: record.labsStudies },
    { label: "Assessment", value: record.assessment },
    { label: "Plan", value: record.plan },
  ]

  sections.forEach(({ label, value }) => {
    if (value) {
      parts.push(sectionTitle(label))
      const formatted = escapeHtml(value).replace(/\n/g, "<br/>")
      parts.push(
        `<p style="font-size: 14px; color: #374151; margin: 0; white-space: pre-wrap;">${formatted}</p>`
      )
    }
  })

  if (parts.length === 0) {
    parts.push(
      `<p style="font-size: 14px; color: #9ca3af; font-style: italic;">Record is empty.</p>`
    )
  }

  return parts.join("\n")
}

function formatResearchBody(messages: ResearchMessage[]): string {
  if (messages.length === 0) {
    return `<p style="font-size: 14px; color: #9ca3af; font-style: italic;">No research messages available.</p>`
  }

  const parts: string[] = []

  messages.forEach((msg) => {
    const isUser = msg.role === "user"
    const bgColor = isUser ? "#eff6ff" : "#ffffff"
    const borderColor = isUser ? "#bfdbfe" : "#e5e7eb"
    const label = isUser ? "You" : "Rxly Research"
    const labelColor = isUser ? "#2563eb" : "#059669"

    parts.push(`
<div style="border: 1px solid ${borderColor}; border-radius: 8px; padding: 12px 16px; margin-bottom: 8px; background: ${bgColor};">
  <div style="font-size: 11px; font-weight: 600; color: ${labelColor}; margin-bottom: 4px;">${label}</div>
  <div style="font-size: 13px; color: #374151; white-space: pre-wrap;">${escapeHtml(msg.content)}</div>
  ${msg.citations.length > 0
        ? `<div style="margin-top: 8px; padding-top: 6px; border-top: 1px solid ${borderColor};">
          ${msg.citations
          .map(
            (c) =>
              `<div style="font-size: 11px; color: #6b7280; margin-bottom: 2px;">&bull; [${escapeHtml(c.source.toUpperCase())}] <a href="${escapeHtml(c.url)}" style="color: #2563eb;">${escapeHtml(c.title)}</a></div>`
          )
          .join("\n")}
        </div>`
        : ""
      }
</div>`)
  })

  return parts.join("\n")
}

function formatPatientHandoutBody(document: PatientHandoutDocument | null): string {
  if (!document || document.conditions.length === 0) {
    return `<p style="font-size: 14px; color: #9ca3af; font-style: italic;">No patient handout available.</p>`
  }

  const sectionOrder: PatientHandoutSectionKey[] = [
    "conditionOverview",
    "signsSymptoms",
    "causesRiskFactors",
    "complications",
    "treatmentOptions",
    "whenToSeekHelp",
    "additionalAdviceFollowUp",
    "disclaimer",
  ]

  const entryMap = new Map(
    document.entries.map((entry) => [entry.conditionId, entry])
  )

  const parts: string[] = []

  document.conditions.forEach((condition) => {
    const entry = entryMap.get(condition.id)
    parts.push(
      `<div style="border: 1px solid #e5e7eb; border-radius: 8px; padding: 16px; margin-bottom: 16px;">`
    )
    parts.push(
      `<h2 style="font-size: 16px; margin: 0 0 2px 0; color: #111827;">${escapeHtml(condition.diseaseName)}</h2>`
    )
    parts.push(
      `<p style="font-size: 12px; margin: 0 0 12px 0; color: #6b7280;">ICD-11: ${escapeHtml(condition.icdCode)}</p>`
    )

    sectionOrder.forEach((sectionKey) => {
      const titleText = PATIENT_HANDOUT_SECTION_LABELS[sectionKey]
      const value = entry?.sections[sectionKey] || ""
      parts.push(sectionTitle(titleText))
      parts.push(
        `<p style="font-size: 14px; color: #374151; margin: 0; white-space: pre-wrap;">${escapeHtml(value || "[Not provided]")}</p>`
      )
    })

    parts.push(`</div>`)
  })

  return parts.join("\n")
}

// ── HTML export (used for email) ──

export function getActiveTabExportHtml(): { html: string; tabLabel: string } {
  const activeTab = useConsultationTabStore.getState().activeTab
  const session = useSessionStore.getState().activeSession
  const sessionTitle = session?.title || "Consultation"
  const tabLabel = TAB_LABELS[activeTab]

  const record = useRecordStore.getState().record
  const patientName = record?.patientName || null

  let bodyHtml = ""

  switch (activeTab) {
    case "insights": {
      const { summary, keyFindings, redFlags, checklistItems } =
        useInsightsStore.getState()
      bodyHtml = formatInsightsBody(
        summary,
        keyFindings,
        redFlags,
        checklistItems
      )
      break
    }
    case "ddx": {
      const { diagnoses } = useDdxStore.getState()
      bodyHtml = formatDdxBody(diagnoses)
      break
    }
    case "record": {
      bodyHtml = formatRecordBody(record)
      break
    }
    case "research": {
      const { messages } = useResearchStore.getState()
      bodyHtml = formatResearchBody(messages)
      break
    }
    case "patientHandout": {
      const { document } = usePatientHandoutStore.getState()
      bodyHtml = formatPatientHandoutBody(document)
      break
    }
  }

  return {
    html: wrapInDocument(tabLabel, sessionTitle, patientName, bodyHtml),
    tabLabel,
  }
}

// ── PDF Export using html2pdf.js ──

export async function generatePdf(): Promise<{ blob: Blob; filename: string }> {
  const { html, tabLabel } = getActiveTabExportHtml()
  const session = useSessionStore.getState().activeSession
  const sessionTitle = session?.title || "Consultation"
  const dateStr = new Date().toISOString().slice(0, 10)
  const filename = `${tabLabel.replace(/\s+/g, "-").toLowerCase()}-${sessionTitle.replace(/\s+/g, "-").toLowerCase()}-${dateStr}.pdf`

  // Dynamically import html2pdf
  const html2pdfModule = (await import("html2pdf.js")) as any
  const html2pdf = html2pdfModule.default || html2pdfModule

  // Create a temporary container for rendering to ensure styles are applied correctly
  const container = document.createElement("div")
  container.innerHTML = html
  // Required so html2pdf can render it accurately before destruction
  container.style.position = "absolute"
  container.style.left = "-9999px"
  document.body.appendChild(container)

  const opt = {
    margin: [15, 0, 15, 0],
    filename,
    image: { type: "jpeg", quality: 0.98 },
    html2canvas: { scale: 2, useCORS: true, letterRendering: true },
    jsPDF: { unit: "mm", format: "a4", orientation: "portrait" },
    pagebreak: { mode: ["css", "legacy"] }
  }

  try {
    const blob = await html2pdf().from(container).set(opt).output("blob")
    return { blob, filename }
  } finally {
    document.body.removeChild(container)
  }
}
