import { describe, expect, it } from "vitest"
import {
  buildStandaloneExportHtml,
  extractStandaloneExportFragment,
} from "./export-document"

describe("export document shell", () => {
  it("builds a centered standalone export document", () => {
    const html = buildStandaloneExportHtml({
      bodyHtml: "<section><h2>Summary</h2><p>Readable export body.</p></section>",
      footerLabel: "Generated by Rxly",
      lang: "ko",
      metaLine: "Live Insights · March 12, 2026",
      title: "Moderate Persistent Asthma",
    })

    expect(html).toContain('<html lang="ko">')
    expect(html).toContain('class="rxly-export-page"')
    expect(html).toContain('class="rxly-export-document"')
    expect(html).toContain("<style>")
    expect(html).toContain("@media print")
    expect(html).toContain("--rxly-export-page-padding-print: 40px 20px 56px;")
    expect(html).toContain("--rxly-export-document-inner-padding:")
    expect(html).toContain("font-size: clamp(1.65rem, 2vw, 2.05rem);")
    expect(html).toContain("font-size: 0.84rem;")
    expect(html).toContain("@page {\n    size: A4;\n    margin: 0;")
    expect(html).toContain(
      '<h1 class="rxly-export-title">Moderate Persistent Asthma</h1>'
    )
    expect(html).toContain(
      '<div class="rxly-export-content"><section><h2>Summary</h2><p>Readable export body.</p></section></div>'
    )
  })

  it("extracts reusable styles and the document fragment", () => {
    const fragment = extractStandaloneExportFragment(`<!doctype html>
<html>
  <head>
    <style>.demo { color: red; }</style>
  </head>
  <body>
    <main class="demo">Shared export content</main>
  </body>
</html>`)

    expect(fragment).toContain("<style>.demo { color: red; }</style>")
    expect(fragment).toContain('<main class="demo">Shared export content</main>')
    expect(fragment).not.toContain("<body")
    expect(fragment).not.toContain("<html")
  })
})
